import { describe, expect, it } from 'vitest'
import { fileURLToPath } from 'node:url'
import { readFileGuarded } from '../src/copier.ts'

const templateNames = ['frontend-astro', 'crm-lite', 'knowledge-base', 'marketing-site', 'support-desk']

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function readTemplateFile(templateName: string, relativePath: string): string {
  const path = fileURLToPath(
    new URL(`../../../templates/${templateName}/${relativePath}`, import.meta.url),
  )
  return readFileGuarded(path).toString('utf8')
}

function readConfig(templateName: string): Record<string, unknown> {
  const parsed: unknown = JSON.parse(readTemplateFile(templateName, 'wrangler.jsonc'))
  if (!isRecord(parsed)) throw new Error(`invalid_wrangler_config: ${templateName}`)
  return parsed
}

describe('Astro Cloudflare template deployment contract', () => {
  for (const templateName of templateNames) {
    it(`${templateName} uses the Astro 6 entrypoint and auto-provisioned session binding`, () => {
      const config = readConfig(templateName)
      expect(config.main).toBe('@astrojs/cloudflare/entrypoints/server')
      expect(config.compatibility_date).toBe('2026-07-07')
      expect(config.compatibility_flags).toEqual(['nodejs_compat'])
      expect(config.kv_namespaces).toEqual([{ binding: 'SESSION' }])
      expect(config).not.toHaveProperty('assets')
      expect(config).not.toHaveProperty('r2_buckets')

      const vars = config.vars
      if (!isRecord(vars)) throw new Error(`invalid_wrangler_vars: ${templateName}`)
      expect(Object.keys(vars).sort()).toEqual([
        'GRAPHQL_ENDPOINT',
        'SUPABASE_ANON_KEY',
        'SUPABASE_URL',
        'WORKSPACE_ID',
      ])

      const generatedEnv = readTemplateFile(templateName, 'src/env.d.ts')
      expect(generatedEnv).toContain('Generated by Wrangler')
      expect(generatedEnv).toContain('SESSION: KVNamespace;')
      expect(generatedEnv).not.toContain('MEDIA_BUCKET')
    })
  }

  it('runs the frontend build, typecheck, and preview without config-hiding wrappers', () => {
    const pkg: unknown = JSON.parse(readTemplateFile('frontend-astro', 'package.json'))
    if (!isRecord(pkg) || !isRecord(pkg.scripts)) throw new Error('invalid_frontend_package')
    expect(pkg.scripts.build).toBe('astro build')
    expect(pkg.scripts.typecheck).toBe('astro check && tsc --noEmit')
    expect(pkg.scripts.preview).toBe('astro preview')
  })
})
