/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false ../knowledge-base/src/env.d.ts` (hash: 41bd49c458f60035b72a128f2781ffab)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	GRAPHQL_ENDPOINT: string;
	WORKSPACE_ID: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GRAPHQL_ENDPOINT" | "WORKSPACE_ID" | "SUPABASE_URL" | "SUPABASE_ANON_KEY">> {}
}
