/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/env.d.ts` (hash: 80b6031129385fa5ebf14eeb996cefe1)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	GRAPHQL_ENDPOINT: string;
	PUBLIC_SITE_URL: string;
	WORKSPACE_ID: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GRAPHQL_ENDPOINT" | "PUBLIC_SITE_URL" | "WORKSPACE_ID" | "SUPABASE_URL" | "SUPABASE_ANON_KEY">> {}
}
