import type { CollectionDef, EventDef, FieldDef, MovpSchema } from '@movp/core-schema'

const HEADER = '-- generated by @movp/codegen - do not edit by hand'

function q(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

function ident(name: string): string {
  if (!/^[a-z][a-z0-9_]*$/.test(name)) throw new Error(`invalid sql identifier: ${name}`)
  return name
}

function sqlType(field: FieldDef): string {
  switch (field.type) {
    case 'number':
      return 'numeric'
    case 'boolean':
      return 'boolean'
    case 'date':
      return 'date'
    case 'datetime':
      return 'timestamptz'
    case 'json':
      return 'jsonb'
    case 'uuid':
      return 'uuid'
    default:
      return 'text'
  }
}

function columnSql(name: string, field: FieldDef): string | null {
  if (field.type === 'relation') return null
  const parts = [`  ${ident(name)} ${sqlType(field)}`]
  if (field.required || field.default !== undefined) parts.push('not null')
  if (field.default !== undefined) {
    parts.push(`default ${typeof field.default === 'string' ? q(field.default) : String(field.default)}`)
  }
  if (field.type === 'enum' && field.values?.length) {
    parts.push(`check (${ident(name)} in (${field.values.map(q).join(', ')}))`)
  }
  return parts.join(' ')
}

function relationHoldsFk(field: FieldDef): boolean {
  return field.type === 'relation' && (field.cardinality === 'many-to-one' || field.cardinality === 'one-to-one')
}

function fkColumnSql(name: string, field: FieldDef): string | null {
  if (!relationHoldsFk(field)) return null
  if (!field.target) throw new Error(`relation field ${name} requires a target`)
  const parts = [`  ${ident(name)}_id uuid`]
  const required = field.required === true
  if (required) parts.push('not null')
  parts.push(`references public.${ident(field.target)}(id)`)
  parts.push(required ? 'on delete cascade' : 'on delete set null')
  return parts.join(' ')
}

function searchableFields(c: CollectionDef): string[] {
  return Object.entries(c.fields)
    .filter(([, field]) => field.searchable && field.type !== 'relation')
    .map(([name]) => name)
}

function embeddableFields(c: CollectionDef): [string, FieldDef][] {
  return Object.entries(c.fields).filter((entry): entry is [string, FieldDef] => entry[1].embeddable === true)
}

function tsvExpression(c: CollectionDef): string {
  const pieces = searchableFields(c).map((name) => `coalesce(new.${ident(name)}, '')`)
  return pieces.length ? pieces.join(` || ' ' || `) : `''`
}

function collectionMetadataSql(c: CollectionDef): string {
  // Platform collections (layer 'platform' or absent) emit BYTE-IDENTICAL SQL to the frozen
  // baseline 20260701000002_movp_generated.sql, which PREDATES the `layer` column (added by
  // 20260713000001_metadata_layer.sql). Emitting `layer` unconditionally would (a) drift the frozen
  // baseline -> `pnpm codegen` throws "generated baseline drift", and (b) reference a column that
  // does not yet exist at baseline apply time. Only project extension codegen (which runs AFTER the
  // platform bundle adds the column) writes `layer = 'project'`.
  const isProject = c.layer === 'project'

  const collectionCols = isProject
    ? '(name, label, label_plural, workspace_scoped, layer)'
    : '(name, label, label_plural, workspace_scoped)'
  const collectionVals = isProject
    ? `(${q(c.name)}, ${q(c.label)}, ${q(c.labelPlural)}, ${String(c.workspaceScoped)}, 'project')`
    : `(${q(c.name)}, ${q(c.label)}, ${q(c.labelPlural)}, ${String(c.workspaceScoped)})`
  const collectionUpdate = isProject
    ? 'label = excluded.label, label_plural = excluded.label_plural, workspace_scoped = excluded.workspace_scoped, layer = excluded.layer'
    : 'label = excluded.label, label_plural = excluded.label_plural, workspace_scoped = excluded.workspace_scoped'

  const fieldCols = isProject
    ? '(collection_name, name, type, label, cardinality, reporting_role, searchable, embeddable, layer)'
    : '(collection_name, name, type, label, cardinality, reporting_role, searchable, embeddable)'
  const fieldRows = Object.entries(c.fields)
    .map(([name, field]) => {
      const cells = [
        q(c.name),
        q(name),
        q(field.type),
        q(field.label),
        field.cardinality ? q(field.cardinality) : 'null',
        field.reporting?.role ? q(field.reporting.role) : 'null',
        String(!!field.searchable),
        String(!!field.embeddable),
      ]
      if (isProject) cells.push(`'project'`)
      return cells.join(', ')
    })
    .map((row) => `  (${row})`)
    .join(',\n')
  const fieldUpdate = isProject
    ? `  type = excluded.type,
  label = excluded.label,
  cardinality = excluded.cardinality,
  reporting_role = excluded.reporting_role,
  searchable = excluded.searchable,
  embeddable = excluded.embeddable,
  layer = excluded.layer`
    : `  type = excluded.type,
  label = excluded.label,
  cardinality = excluded.cardinality,
  reporting_role = excluded.reporting_role,
  searchable = excluded.searchable,
  embeddable = excluded.embeddable`

  return `
insert into public.movp_collections ${collectionCols}
values ${collectionVals}
on conflict (name) do update set ${collectionUpdate};

insert into public.movp_fields ${fieldCols}
values
${fieldRows}
on conflict (collection_name, name) do update set
${fieldUpdate};`
}

function ftsSql(c: CollectionDef): string {
  if (searchableFields(c).length === 0) return ''
  return `
create or replace function public.${ident(c.name)}_search_vector_update()
returns trigger
language plpgsql
as $$
begin
  new.search_vector := to_tsvector('english', ${tsvExpression(c)});
  return new;
end;
$$;

create trigger ${ident(c.name)}_search_vector_tg
  before insert or update on public.${ident(c.name)}
  for each row execute function public.${ident(c.name)}_search_vector_update();

create index ${ident(c.name)}_search_idx on public.${ident(c.name)} using gin (search_vector);`
}

function embedTriggerSql(c: CollectionDef, fieldName: string): string {
  return `
create or replace function public.${ident(c.name)}_${ident(fieldName)}_enqueue_embed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hash text;
begin
  v_hash := encode(extensions.digest(coalesce(new.${ident(fieldName)}, ''), 'sha256'), 'hex');
  if tg_op = 'UPDATE' and v_hash = encode(extensions.digest(coalesce(old.${ident(fieldName)}, ''), 'sha256'), 'hex') then
    return new;
  end if;

  insert into movp_internal.movp_jobs (kind, idempotency_key, payload, workspace_id)
  values (
    'embed',
    ${q(c.name)} || ':' || new.id::text || ':${fieldName}:' || v_hash,
    jsonb_build_object('source_table', ${q(c.name)}, 'source_id', new.id, 'field', ${q(fieldName)}, 'content_hash', v_hash),
    new.workspace_id
  )
  on conflict (kind, idempotency_key) do nothing;
  return new;
end;
$$;
revoke all on function public.${ident(c.name)}_${ident(fieldName)}_enqueue_embed() from public, anon, authenticated;

create trigger ${ident(c.name)}_${ident(fieldName)}_enqueue_embed_tg
  after insert or update on public.${ident(c.name)}
  for each row execute function public.${ident(c.name)}_${ident(fieldName)}_enqueue_embed();`
}

function deleteChunksSql(c: CollectionDef): string {
  return `
create or replace function public.${ident(c.name)}_delete_chunks()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.search_chunk where source_table = ${q(c.name)} and source_id = old.id;
  return old;
end;
$$;
revoke all on function public.${ident(c.name)}_delete_chunks() from public, anon, authenticated;

create trigger ${ident(c.name)}_delete_chunks_tg
  after delete on public.${ident(c.name)}
  for each row execute function public.${ident(c.name)}_delete_chunks();`
}

function rlsSql(c: CollectionDef): string {
  if (!c.workspaceScoped) {
    return `
alter table public.${ident(c.name)} enable row level security;
grant select on public.${ident(c.name)} to authenticated;
grant select, insert, update, delete on public.${ident(c.name)} to service_role;
create policy ${ident(c.name)}_read on public.${ident(c.name)} for select to authenticated using (true);`
  }
  return `
alter table public.${ident(c.name)} enable row level security;
grant select, insert, update, delete on public.${ident(c.name)} to authenticated;
grant select, insert, update, delete on public.${ident(c.name)} to service_role;
create policy ${ident(c.name)}_rw on public.${ident(c.name)} for all to authenticated
  using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));`
}

function eventCatalogSeedSql(events: EventDef[]): string {
  if (events.length === 0) return ''

  const rows = events
    .map((event) =>
      [
        q(event.key),
        q(event.domain),
        q(event.label ?? event.key),
        q(JSON.stringify(event.payloadSchema)),
        String(event.version),
        'true',
        event.description ? q(event.description) : 'null',
      ].join(', '),
    )
    .map((row) => `  (${row})`)
    .join(',\n')

  return `
create unique index if not exists event_type_key_unique on public.event_type (key);
insert into public.event_type (key, domain, label, payload_schema, schema_version, active, description)
values
${rows}
on conflict (key) do update set
  domain = excluded.domain,
  label = excluded.label,
  payload_schema = excluded.payload_schema,
  schema_version = excluded.schema_version,
  active = excluded.active,
  description = excluded.description;`
}

export function emitSharedInfraSql(): string {
  return `
create extension if not exists vector with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create schema if not exists movp_internal;

create table if not exists public.movp_collections (
  name text primary key,
  label text not null,
  label_plural text not null,
  workspace_scoped boolean not null
);

create table if not exists public.movp_fields (
  collection_name text not null references public.movp_collections(name) on delete cascade,
  name text not null,
  type text not null,
  label text not null,
  cardinality text,
  reporting_role text,
  searchable boolean not null default false,
  embeddable boolean not null default false,
  primary key (collection_name, name)
);
grant select on public.movp_collections to authenticated;
grant select on public.movp_fields to authenticated;
grant select, insert, update, delete on public.movp_collections to service_role;
grant select, insert, update, delete on public.movp_fields to service_role;

create table if not exists movp_internal.movp_job_kind (
  kind text primary key
);
insert into movp_internal.movp_job_kind (kind)
values ('embed'), ('webhook'), ('notify')
on conflict (kind) do nothing;
alter table movp_internal.movp_job_kind enable row level security;
revoke all on movp_internal.movp_job_kind from anon, authenticated;
grant all on movp_internal.movp_job_kind to service_role;

create table if not exists movp_internal.movp_jobs (
  id uuid primary key default gen_random_uuid(),
  kind text not null references movp_internal.movp_job_kind(kind),
  idempotency_key text not null,
  payload jsonb not null default '{}',
  workspace_id uuid references public.workspace(id) on delete cascade,
  attempts int not null default 0,
  max_attempts int not null default 8,
  status text not null default 'pending' check (status in ('pending', 'running', 'done', 'failed', 'dead')),
  next_run_at timestamptz not null default now(),
  locked_by text,
  locked_at timestamptz,
  lease_expires_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kind, idempotency_key)
);
alter table movp_internal.movp_jobs enable row level security;
create index if not exists movp_jobs_due on movp_internal.movp_jobs (status, next_run_at, lease_expires_at);
revoke all on movp_internal.movp_jobs from anon, authenticated;
grant all on movp_internal.movp_jobs to service_role;

create table if not exists public.search_chunk (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  source_table text not null,
  source_id uuid not null,
  field text not null,
  chunk_index int not null,
  content text not null,
  embedding extensions.vector(384) not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  unique (source_table, source_id, field, chunk_index)
);
alter table public.search_chunk enable row level security;
grant select on public.search_chunk to authenticated;
grant select, insert, update, delete on public.search_chunk to service_role;
create policy search_chunk_read on public.search_chunk
  for select to authenticated
  using (public.is_workspace_member(workspace_id));
create index if not exists search_chunk_hnsw on public.search_chunk using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.match_chunks(
  query_embedding extensions.vector(384),
  ws uuid,
  source_table_filter text default null,
  match_count int default 10
)
returns table(source_table text, source_id uuid, field text, chunk_index int, content text, distance float)
language plpgsql
set search_path = ''
as $$
begin
  perform set_config('hnsw.iterative_scan', 'strict_order', true);
  return query
  select c.source_table, c.source_id, c.field, c.chunk_index, c.content,
         c.embedding OPERATOR(extensions.<=>) query_embedding as distance
    from public.search_chunk c
   where c.workspace_id = ws
     and (source_table_filter is null or c.source_table = source_table_filter)
   order by c.embedding OPERATOR(extensions.<=>) query_embedding
   limit least(greatest(match_count, 1), 50);
end;
$$;
grant execute on function public.match_chunks(extensions.vector(384), uuid, text, int) to authenticated;

create table if not exists public.edges (
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  src_type text not null,
  src_id uuid not null,
  rel text not null,
  dst_type text not null,
  dst_id uuid not null,
  created_at timestamptz not null default now(),
  unique (workspace_id, src_type, src_id, rel, dst_type, dst_id)
);
alter table public.edges enable row level security;
grant select, insert, update, delete on public.edges to authenticated;
grant select, insert, update, delete on public.edges to service_role;
create policy edges_rw on public.edges for all to authenticated
  using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));
create index if not exists edges_src_idx on public.edges (src_type, src_id);
create index if not exists edges_dst_idx on public.edges (dst_type, dst_id);`
}

export function emitCollectionSql(c: CollectionDef): string {
  const cols = [
    '  id uuid primary key default gen_random_uuid()',
    c.workspaceScoped ? '  workspace_id uuid not null references public.workspace(id) on delete cascade' : null,
    ...Object.entries(c.fields).map(([name, field]) => columnSql(name, field)),
    ...Object.entries(c.fields).map(([name, field]) => fkColumnSql(name, field)),
    searchableFields(c).length ? '  search_vector tsvector' : null,
    '  created_at timestamptz not null default now()',
    '  updated_at timestamptz not null default now()',
  ].filter(Boolean)

  return `
create table if not exists public.${ident(c.name)} (
${cols.join(',\n')}
);
${rlsSql(c)}
${ftsSql(c)}
${embeddableFields(c)
  .map(([fieldName]) => embedTriggerSql(c, fieldName))
  .join('\n')}
${deleteChunksSql(c)}
${collectionMetadataSql(c)}
`
}

export function emitSqlMigration(
  schema: MovpSchema,
  opts: { excludeCollections?: readonly string[]; excludeEvents?: readonly string[] } = {},
): string {
  const excludedCollections = new Set(opts.excludeCollections ?? [])
  const excludedEvents = new Set(opts.excludeEvents ?? [])
  const collections = schema.collections.filter((collection) => !excludedCollections.has(collection.name))
  const events = schema.events.filter((event) => !excludedEvents.has(event.key))
  return `${HEADER}\n\n${emitSharedInfraSql()}\n\n${collections.map(emitCollectionSql).join('\n')}\n${eventCatalogSeedSql(events)}`
}

// Post-freeze collections and event catalog rows share the baseline emitters so their DDL stays identical.
export function emitDeltaSql(
  schema: MovpSchema,
  owned: { collections?: readonly string[]; events?: readonly string[] },
): string {
  const collections = (owned.collections ?? []).map((name) => {
    const collection = schema.collections.find((entry) => entry.name === name)
    if (!collection) throw new Error(`delta collection not registered: ${name}`)
    return emitCollectionSql(collection)
  })
  const eventKeys = new Set(owned.events ?? [])
  const events = schema.events.filter((event) => eventKeys.has(event.key))
  for (const key of owned.events ?? []) {
    if (!events.some((event) => event.key === key)) {
      throw new Error(`delta event not registered: ${key}`)
    }
  }
  return `${HEADER}\n${collections.join('\n')}\n${eventCatalogSeedSql(events)}`
}

function assertProjectLayer(collection: CollectionDef): void {
  if (collection.layer !== 'project') {
    throw new Error(
      `platform_row_delete_forbidden: collection "${collection.name}" is layer="${collection.layer}"`,
    )
  }
}

function projectOwnershipMarkers(collections: CollectionDef[], events: EventDef[]): string {
  return [
    ...collections.map((collection) => `-- movp-project-collection: ${collection.name}`),
    ...events.map((event) => `-- movp-project-event: ${event.key}`),
  ].join('\n')
}

export function emitProjectMigration(
  schema: MovpSchema,
  opts: { excludeCollections?: readonly string[]; excludeEvents?: readonly string[] } = {},
): string {
  const excludedCollections = new Set(opts.excludeCollections ?? [])
  const excludedEvents = new Set(opts.excludeEvents ?? [])
  const collections = schema.projectCollections.filter(
    (collection) => !excludedCollections.has(collection.name),
  )
  for (const collection of collections) assertProjectLayer(collection)
  const events = schema.projectEvents.filter((event) => !excludedEvents.has(event.key))
  return `${HEADER}\n${projectOwnershipMarkers(collections, events)}\n${collections.map(emitCollectionSql).join('\n')}\n${eventCatalogSeedSql(events)}`
}

export function emitProjectDeltaSql(
  schema: MovpSchema,
  owned: { collections?: readonly string[]; events?: readonly string[] },
): string {
  const collections = (owned.collections ?? []).map((name) => {
    const collection = schema.projectCollections.find((entry) => entry.name === name)
    if (!collection) throw new Error(`delta collection not registered: ${name}`)
    assertProjectLayer(collection)
    return emitCollectionSql(collection)
  })
  const eventKeys = new Set(owned.events ?? [])
  const events = schema.projectEvents.filter((event) => eventKeys.has(event.key))
  for (const key of owned.events ?? []) {
    if (!events.some((event) => event.key === key)) throw new Error(`delta event not registered: ${key}`)
  }
  const collectionDefs = (owned.collections ?? []).map((name) => {
    const collection = schema.projectCollections.find((entry) => entry.name === name)
    if (!collection) throw new Error(`delta collection not registered: ${name}`)
    return collection
  })
  return `${HEADER}\n${projectOwnershipMarkers(collectionDefs, events)}\n${collections.join('\n')}\n${eventCatalogSeedSql(events)}`
}

export function emitProjectMetadataPrune(schema: MovpSchema): string {
  for (const collection of schema.projectCollections) assertProjectLayer(collection)
  const collectionNames = schema.projectCollections.map((collection) => q(collection.name)).sort()
  const fieldKeys = schema.projectCollections
    .flatMap((collection) => Object.keys(collection.fields).map(
      (field) => `(${q(collection.name)}, ${q(field)})`,
    ))
    .sort()
  const collectionList = collectionNames.length > 0 ? collectionNames.join(', ') : "''"
  const fieldList = fieldKeys.length > 0 ? fieldKeys.join(', ') : '(null, null)'
  return `
delete from public.movp_fields where layer = 'project' and (collection_name, name) not in (${fieldList});
delete from public.movp_collections where layer = 'project' and name not in (${collectionList});`
}
