import type { CollectionDef, FieldDef, MovpSchema } from '@movp/core-schema'

const HEADER = '// generated by @movp/codegen - do not edit by hand'

function pascal(name: string): string {
  return name
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function scalarType(field: FieldDef): string {
  switch (field.type) {
    case 'enum':
      return (field.values ?? []).map((v) => `'${v}'`).join(' | ')
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'json':
      return 'Record<string, unknown>'
    default:
      return 'string'
  }
}

function rowFieldType(field: FieldDef): string {
  const t = scalarType(field)
  return field.required || field.default !== undefined ? t : `${t} | null`
}

function createFieldOptional(field: FieldDef): boolean {
  return !field.required || field.default !== undefined
}

function dataFields(c: CollectionDef): [string, FieldDef][] {
  return Object.entries(c.fields).filter((entry): entry is [string, FieldDef] => entry[1].type !== 'relation')
}

function relationHoldsFk(field: FieldDef): boolean {
  return field.type === 'relation' && (field.cardinality === 'many-to-one' || field.cardinality === 'one-to-one')
}

function fkFields(c: CollectionDef): [string, FieldDef][] {
  return Object.entries(c.fields).filter((entry): entry is [string, FieldDef] => relationHoldsFk(entry[1]))
}

function emitCollectionTypes(c: CollectionDef): string {
  const name = pascal(c.name)
  const out: string[] = []

  out.push(`export interface ${name}Row {`)
  out.push('  id: string')
  if (c.workspaceScoped) out.push('  workspace_id: string')
  for (const [fieldName, field] of dataFields(c)) {
    out.push(`  ${fieldName}: ${rowFieldType(field)}`)
  }
  for (const [fieldName, field] of fkFields(c)) {
    out.push(`  ${fieldName}_id: ${field.required === true ? 'string' : 'string | null'}`)
  }
  out.push('  created_at: string')
  out.push('  updated_at: string')
  out.push('}')
  out.push('')

  out.push(`export interface ${name}Create {`)
  if (c.workspaceScoped) out.push('  workspace_id: string')
  for (const [fieldName, field] of dataFields(c)) {
    const optional = createFieldOptional(field) ? '?' : ''
    out.push(`  ${fieldName}${optional}: ${scalarType(field)}`)
  }
  for (const [fieldName, field] of fkFields(c)) {
    const optional = createFieldOptional(field) ? '?' : ''
    out.push(`  ${fieldName}_id${optional}: string`)
  }
  out.push('}')
  out.push('')

  out.push(`export interface ${name}Update {`)
  for (const [fieldName, field] of dataFields(c)) {
    out.push(`  ${fieldName}?: ${scalarType(field)}`)
  }
  for (const [fieldName] of fkFields(c)) {
    out.push(`  ${fieldName}_id?: string`)
  }
  out.push('}')

  return out.join('\n')
}

export function emitTypes(schema: MovpSchema): string {
  return `${HEADER}\n\n${schema.collections.map(emitCollectionTypes).join('\n\n')}\n`
}
