import type { CollectionDef, FieldDef, MovpSchema } from '@movp/core-schema'

const HEADER = '-- generated by @movp/codegen - do not edit by hand'

function ident(name: string): string {
  if (!/^[a-z][a-z0-9_]*$/.test(name)) throw new Error(`invalid sql identifier: ${name}`)
  return name
}

function isFkRelation(field: FieldDef): boolean {
  return field.type === 'relation' && (field.cardinality === 'many-to-one' || field.cardinality === 'one-to-one')
}

function reportingFields(collection: CollectionDef): [string, FieldDef][] {
  return Object.entries(collection.fields).filter(([, field]) => field.reporting?.role !== undefined)
}

function viewColumns(collection: CollectionDef): string[] {
  const columns = ['id']
  if (collection.workspaceScoped) columns.push('workspace_id')

  for (const [name, field] of Object.entries(collection.fields)) {
    if (isFkRelation(field)) {
      columns.push(`${ident(name)}_id`)
      continue
    }
    if (field.reporting?.role === undefined) continue
    if (field.type === 'relation') {
      throw new Error(
        `reporting role on non-FK relation ${collection.name}.${name} is not supported (many-to-many has no column)`,
      )
    }
    columns.push(ident(name))
  }

  columns.push('created_at', 'updated_at')
  return columns
}

export function emitReportingViewSql(collection: CollectionDef): string {
  const name = ident(collection.name)
  return `
create or replace view reporting.v_${name}
with (security_invoker = true) as
select ${viewColumns(collection).join(', ')}
from public.${name};
grant select on reporting.v_${name} to authenticated, service_role;`
}

export function emitReportingSql(schema: MovpSchema): string {
  const collections = schema.collections.filter((collection) => reportingFields(collection).length > 0)
  return `${HEADER}
-- reporting schema: SECURITY-INVOKER views over collections with reporting metadata.
-- RLS on the underlying tables still binds — a member sees only their workspaces.
-- movp_internal is NOT exposed here; event/job analytics are member-gated SECURITY
-- DEFINER RPCs (20260711000002_reporting_analytics.sql, Stage C4b).

create schema if not exists reporting;
grant usage on schema reporting to authenticated, service_role;
${collections.map(emitReportingViewSql).join('\n')}
`
}
