import { note, schema } from '@movp/core-schema'
import { describe, expect, it } from 'vitest'
import { emitCollectionSql, emitSharedInfraSql, emitSqlMigration } from '../src/index.ts'

describe('emitSharedInfraSql', () => {
  const sql = emitSharedInfraSql()

  it('creates shared search, graph, metadata, and queue infra', () => {
    expect(sql).toContain('create extension if not exists vector with schema extensions;')
    expect(sql).toContain('create schema if not exists movp_internal;')
    expect(sql).toContain('create table if not exists movp_internal.movp_job_kind')
    expect(sql).toContain("values ('embed'), ('webhook'), ('notify')")
    expect(sql).toContain('kind text not null references movp_internal.movp_job_kind(kind)')
    expect(sql).toContain('create table if not exists movp_internal.movp_jobs')
    expect(sql).not.toContain("check (kind" + " in ('embed', 'webhook', 'notify'))")
    expect(sql).toContain('unique (kind, idempotency_key)')
    expect(sql).toContain('embedding extensions.vector(384) not null')
    expect(sql).toContain('using hnsw (embedding extensions.vector_cosine_ops)')
    expect(sql).toContain('create or replace function public.match_chunks')
    expect(sql).toContain("set_config('hnsw.iterative_scan', 'strict_order', true)")
    expect(sql).toContain('limit least(greatest(match_count, 1), 50)')
    expect(sql).toContain('create table if not exists public.edges')
    expect(sql).toContain('create table if not exists public.movp_collections')
    expect(sql).toContain('grant select, insert, update, delete on public.movp_collections to service_role;')
    expect(sql).toContain('grant select, insert, update, delete on public.search_chunk to service_role;')
    expect(sql).toContain('grant select, insert, update, delete on public.edges to service_role;')
  })
})

describe('emitCollectionSql(note)', () => {
  const sql = emitCollectionSql(note)

  it('creates table, FTS, RLS, embed trigger, cleanup trigger, and metadata', () => {
    expect(sql).toContain('create table if not exists public.note')
    expect(sql).toContain('grant select, insert, update, delete on public.note to service_role;')
    expect(sql).toContain('workspace_id uuid not null references public.workspace(id) on delete cascade')
    expect(sql).toContain('title text not null')
    expect(sql).toContain("status text not null default 'draft' check (status in ('draft', 'published', 'archived'))")
    expect(sql).toContain('search_vector tsvector')
    expect(sql).toContain('create index note_search_idx on public.note using gin (search_vector);')
    expect(sql).toContain('create policy note_rw on public.note for all to authenticated')
    expect(sql).toContain('create or replace function public.note_body_enqueue_embed()')
    expect(sql).toContain("set search_path = ''")
    expect(sql).toContain('insert into movp_internal.movp_jobs')
    expect(sql).toContain('create or replace function public.note_delete_chunks()')
    expect(sql).toContain('delete from public.search_chunk')
    expect(sql).toContain("values ('note', 'Note', 'Notes', true)")
    expect(sql).toContain("('note', 'tags', 'relation', 'Tags', 'many-to-many', null, false, false)")
  })
})

describe('emitSqlMigration', () => {
  const sql = emitSqlMigration(schema)

  it('emits generated header and orders shared infra before collection DDL', () => {
    expect(sql.startsWith('-- generated by @movp/codegen - do not edit by hand')).toBe(true)
    expect(sql.indexOf('movp_internal.movp_jobs')).toBeLessThan(sql.indexOf('create table if not exists public.note'))
    expect(sql).toContain('create table if not exists public.tag')
  })
})
