import { schema } from '@movp/core-schema'
import { describe, expect, it } from 'vitest'
import { emitTypes } from '../src/index.ts'

describe('emitTypes', () => {
  const ts = emitTypes(schema)

  it('emits generated file header', () => {
    expect(ts.startsWith('// generated by @movp/codegen - do not edit by hand')).toBe(true)
  })

  it('emits Note row/create/update types', () => {
    expect(ts).toContain('export interface NoteRow {')
    expect(ts).toContain('  workspace_id: string')
    expect(ts).toContain('  title: string')
    expect(ts).toContain('  body: string | null')
    expect(ts).toContain("  status: 'draft' | 'published' | 'archived'")
    expect(ts).toContain('export interface NoteCreate {')
    expect(ts).toContain('  title: string')
    expect(ts).toContain('  body?: string')
    expect(ts).toContain("  status?: 'draft' | 'published' | 'archived'")
    expect(ts).toContain('export interface NoteUpdate {')
  })

  it('emits Tag types and excludes relation fields', () => {
    expect(ts).toContain('export interface TagRow {')
    expect(ts).toContain('  name: string')
    expect(ts).not.toContain('tags')
  })
})
