-- generated by @movp/codegen - do not edit by hand


create extension if not exists vector with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create schema if not exists movp_internal;

create table if not exists public.movp_collections (
  name text primary key,
  label text not null,
  label_plural text not null,
  workspace_scoped boolean not null
);

create table if not exists public.movp_fields (
  collection_name text not null references public.movp_collections(name) on delete cascade,
  name text not null,
  type text not null,
  label text not null,
  cardinality text,
  reporting_role text,
  searchable boolean not null default false,
  embeddable boolean not null default false,
  primary key (collection_name, name)
);

create table if not exists movp_internal.movp_jobs (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('embed', 'webhook', 'notify')),
  idempotency_key text not null,
  payload jsonb not null default '{}',
  workspace_id uuid references public.workspace(id) on delete cascade,
  attempts int not null default 0,
  max_attempts int not null default 8,
  status text not null default 'pending' check (status in ('pending', 'running', 'done', 'failed', 'dead')),
  next_run_at timestamptz not null default now(),
  locked_by text,
  locked_at timestamptz,
  lease_expires_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kind, idempotency_key)
);
alter table movp_internal.movp_jobs enable row level security;
create index if not exists movp_jobs_due on movp_internal.movp_jobs (status, next_run_at, lease_expires_at);
revoke all on movp_internal.movp_jobs from anon, authenticated;
grant all on movp_internal.movp_jobs to service_role;

create table if not exists public.search_chunk (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  source_table text not null,
  source_id uuid not null,
  field text not null,
  chunk_index int not null,
  content text not null,
  embedding extensions.vector(384) not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  unique (source_table, source_id, field, chunk_index)
);
alter table public.search_chunk enable row level security;
create policy search_chunk_read on public.search_chunk
  for select to authenticated
  using (public.is_workspace_member(workspace_id));
create index if not exists search_chunk_hnsw on public.search_chunk using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.match_chunks(
  query_embedding extensions.vector(384),
  ws uuid,
  source_table_filter text default null,
  match_count int default 10
)
returns table(source_table text, source_id uuid, field text, chunk_index int, content text, distance float)
language plpgsql
set search_path = ''
as $$
begin
  perform set_config('hnsw.iterative_scan', 'strict_order', true);
  return query
  select c.source_table, c.source_id, c.field, c.chunk_index, c.content, c.embedding <=> query_embedding as distance
    from public.search_chunk c
   where c.workspace_id = ws
     and (source_table_filter is null or c.source_table = source_table_filter)
   order by c.embedding <=> query_embedding
   limit least(greatest(match_count, 1), 50);
end;
$$;
grant execute on function public.match_chunks(extensions.vector(384), uuid, text, int) to authenticated;

create table if not exists public.edges (
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  src_type text not null,
  src_id uuid not null,
  rel text not null,
  dst_type text not null,
  dst_id uuid not null,
  created_at timestamptz not null default now(),
  unique (workspace_id, src_type, src_id, rel, dst_type, dst_id)
);
alter table public.edges enable row level security;
create policy edges_rw on public.edges for all to authenticated
  using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));
create index if not exists edges_src_idx on public.edges (src_type, src_id);
create index if not exists edges_dst_idx on public.edges (dst_type, dst_id);


create table if not exists public.note (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  title text not null,
  body text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  search_vector tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.note enable row level security;
create policy note_rw on public.note for all to authenticated
  using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));

create or replace function public.note_search_vector_update()
returns trigger
language plpgsql
as $$
begin
  new.search_vector := to_tsvector('english', coalesce(new.title, '') || ' ' || coalesce(new.body, ''));
  return new;
end;
$$;

create trigger note_search_vector_tg
  before insert or update on public.note
  for each row execute function public.note_search_vector_update();

create index note_search_idx on public.note using gin (search_vector);

create or replace function public.note_body_enqueue_embed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hash text;
begin
  v_hash := encode(extensions.digest(coalesce(new.body, ''), 'sha256'), 'hex');
  if tg_op = 'UPDATE' and v_hash = encode(extensions.digest(coalesce(old.body, ''), 'sha256'), 'hex') then
    return new;
  end if;

  insert into movp_internal.movp_jobs (kind, idempotency_key, payload, workspace_id)
  values (
    'embed',
    'note' || ':' || new.id::text || ':body:' || v_hash,
    jsonb_build_object('source_table', 'note', 'source_id', new.id, 'field', 'body', 'content_hash', v_hash),
    new.workspace_id
  )
  on conflict (kind, idempotency_key) do nothing;
  return new;
end;
$$;
revoke all on function public.note_body_enqueue_embed() from public, anon, authenticated;

create trigger note_body_enqueue_embed_tg
  after insert or update on public.note
  for each row execute function public.note_body_enqueue_embed();

create or replace function public.note_delete_chunks()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.search_chunk where source_table = 'note' and source_id = old.id;
  return old;
end;
$$;
revoke all on function public.note_delete_chunks() from public, anon, authenticated;

create trigger note_delete_chunks_tg
  after delete on public.note
  for each row execute function public.note_delete_chunks();

insert into public.movp_collections (name, label, label_plural, workspace_scoped)
values ('note', 'Note', 'Notes', true)
on conflict (name) do update set label = excluded.label, label_plural = excluded.label_plural, workspace_scoped = excluded.workspace_scoped;

insert into public.movp_fields (collection_name, name, type, label, cardinality, reporting_role, searchable, embeddable)
values
  ('note', 'title', 'text', 'Title', null, null, true, false),
  ('note', 'body', 'richText', 'Body', null, null, true, true),
  ('note', 'status', 'enum', 'Status', null, 'dimension', false, false),
  ('note', 'tags', 'relation', 'Tags', 'many-to-many', null, false, false)
on conflict (collection_name, name) do update set
  type = excluded.type,
  label = excluded.label,
  cardinality = excluded.cardinality,
  reporting_role = excluded.reporting_role,
  searchable = excluded.searchable,
  embeddable = excluded.embeddable;


create table if not exists public.tag (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  name text not null,
  search_vector tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.tag enable row level security;
create policy tag_rw on public.tag for all to authenticated
  using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));

create or replace function public.tag_search_vector_update()
returns trigger
language plpgsql
as $$
begin
  new.search_vector := to_tsvector('english', coalesce(new.name, ''));
  return new;
end;
$$;

create trigger tag_search_vector_tg
  before insert or update on public.tag
  for each row execute function public.tag_search_vector_update();

create index tag_search_idx on public.tag using gin (search_vector);


create or replace function public.tag_delete_chunks()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.search_chunk where source_table = 'tag' and source_id = old.id;
  return old;
end;
$$;
revoke all on function public.tag_delete_chunks() from public, anon, authenticated;

create trigger tag_delete_chunks_tg
  after delete on public.tag
  for each row execute function public.tag_delete_chunks();

insert into public.movp_collections (name, label, label_plural, workspace_scoped)
values ('tag', 'Tag', 'Tags', true)
on conflict (name) do update set label = excluded.label, label_plural = excluded.label_plural, workspace_scoped = excluded.workspace_scoped;

insert into public.movp_fields (collection_name, name, type, label, cardinality, reporting_role, searchable, embeddable)
values
  ('tag', 'name', 'text', 'Name', null, null, true, false)
on conflict (collection_name, name) do update set
  type = excluded.type,
  label = excluded.label,
  cardinality = excluded.cardinality,
  reporting_role = excluded.reporting_role,
  searchable = excluded.searchable,
  embeddable = excluded.embeddable;
