-- generated by @movp/codegen - do not edit by hand
-- reporting schema: SECURITY-INVOKER views over collections with reporting metadata.
-- RLS on the underlying tables still binds — a member sees only their workspaces.
-- movp_internal is NOT exposed here; event/job analytics are member-gated SECURITY
-- DEFINER RPCs (20260711000002_reporting_analytics.sql, Stage C4b).

create schema if not exists reporting;
grant usage on schema reporting to authenticated, service_role;

create or replace view reporting.v_event_type
with (security_invoker = true) as
select id, key, domain, created_at, updated_at
from public.event_type;
grant select on reporting.v_event_type to authenticated, service_role;

create or replace view reporting.v_note
with (security_invoker = true) as
select id, workspace_id, status, created_at, updated_at
from public.note;
grant select on reporting.v_note to authenticated, service_role;

create or replace view reporting.v_reaction
with (security_invoker = true) as
select id, workspace_id, kind, created_at, updated_at
from public.reaction;
grant select on reporting.v_reaction to authenticated, service_role;

create or replace view reporting.v_task_status_option
with (security_invoker = true) as
select id, workspace_id, category, created_at, updated_at
from public.task_status_option;
grant select on reporting.v_task_status_option to authenticated, service_role;

create or replace view reporting.v_content_type
with (security_invoker = true) as
select id, workspace_id, moderation_policy, approval_policy, created_at, updated_at
from public.content_type;
grant select on reporting.v_content_type to authenticated, service_role;

create or replace view reporting.v_content_item
with (security_invoker = true) as
select id, workspace_id, content_type_id, status, created_at, updated_at
from public.content_item;
grant select on reporting.v_content_item to authenticated, service_role;

create or replace view reporting.v_content_approval
with (security_invoker = true) as
select id, workspace_id, content_item_id, state, policy, approved_revision_id, created_at, updated_at
from public.content_approval;
grant select on reporting.v_content_approval to authenticated, service_role;

create or replace view reporting.v_content_publish_event
with (security_invoker = true) as
select id, workspace_id, content_item_id, action, revision_id, created_at, updated_at
from public.content_publish_event;
grant select on reporting.v_content_publish_event to authenticated, service_role;

create or replace view reporting.v_content_schedule
with (security_invoker = true) as
select id, workspace_id, content_item_id, revision_id, state, created_at, updated_at
from public.content_schedule;
grant select on reporting.v_content_schedule to authenticated, service_role;

create or replace view reporting.v_asset
with (security_invoker = true) as
select id, workspace_id, mime, size_bytes, created_at, updated_at
from public.asset;
grant select on reporting.v_asset to authenticated, service_role;

create or replace view reporting.v_content_seo
with (security_invoker = true) as
select id, workspace_id, content_item_id, score, created_at, updated_at
from public.content_seo;
grant select on reporting.v_content_seo to authenticated, service_role;

create or replace view reporting.v_marketing_plan
with (security_invoker = true) as
select id, workspace_id, period_start, period_end, status, created_at, updated_at
from public.marketing_plan;
grant select on reporting.v_marketing_plan to authenticated, service_role;

create or replace view reporting.v_campaign
with (security_invoker = true) as
select id, workspace_id, marketing_plan_id, start_date, end_date, priority, rank, status, created_at, updated_at
from public.campaign;
grant select on reporting.v_campaign to authenticated, service_role;

create or replace view reporting.v_campaign_channel
with (security_invoker = true) as
select id, workspace_id, campaign_id, channel_type, created_at, updated_at
from public.campaign_channel;
grant select on reporting.v_campaign_channel to authenticated, service_role;

create or replace view reporting.v_campaign_deliverable
with (security_invoker = true) as
select id, workspace_id, campaign_id, channel_id, deliverable_type, created_at, updated_at
from public.campaign_deliverable;
grant select on reporting.v_campaign_deliverable to authenticated, service_role;

create or replace view reporting.v_campaign_calendar_event
with (security_invoker = true) as
select id, workspace_id, campaign_id, event_date, event_type, created_at, updated_at
from public.campaign_calendar_event;
grant select on reporting.v_campaign_calendar_event to authenticated, service_role;

create or replace view reporting.v_campaign_metric
with (security_invoker = true) as
select id, workspace_id, campaign_id, deliverable_id, channel_id, metric_key, value, unit, measured_at, created_at, updated_at
from public.campaign_metric;
grant select on reporting.v_campaign_metric to authenticated, service_role;

create or replace view reporting.v_campaign_segment
with (security_invoker = true) as
select id, workspace_id, campaign_id, targeting_role, created_at, updated_at
from public.campaign_segment;
grant select on reporting.v_campaign_segment to authenticated, service_role;

create or replace view reporting.v_platform_event
with (security_invoker = true) as
select id, workspace_id, event_type, subject_type, source, occurred_at, created_at, updated_at
from public.platform_event;
grant select on reporting.v_platform_event to authenticated, service_role;

create or replace view reporting.v_segment
with (security_invoker = true) as
select id, workspace_id, active, mode, created_at, updated_at
from public.segment;
grant select on reporting.v_segment to authenticated, service_role;

create or replace view reporting.v_segment_rule
with (security_invoker = true) as
select id, workspace_id, segment_id, active, created_at, updated_at
from public.segment_rule;
grant select on reporting.v_segment_rule to authenticated, service_role;

create or replace view reporting.v_segment_membership
with (security_invoker = true) as
select id, workspace_id, segment_id, subject_type, matched_rule_id, created_at, updated_at
from public.segment_membership;
grant select on reporting.v_segment_membership to authenticated, service_role;

create or replace view reporting.v_segment_snapshot
with (security_invoker = true) as
select id, workspace_id, segment_id, reason, member_count, created_at, updated_at
from public.segment_snapshot;
grant select on reporting.v_segment_snapshot to authenticated, service_role;

create or replace view reporting.v_segment_recompute_run
with (security_invoker = true) as
select id, workspace_id, segment_id, mode, added_count, removed_count, evaluated_count, created_at, updated_at
from public.segment_recompute_run;
grant select on reporting.v_segment_recompute_run to authenticated, service_role;

create or replace view reporting.v_automation_rule
with (security_invoker = true) as
select id, workspace_id, trigger_event_type_id, action_type, created_at, updated_at
from public.automation_rule;
grant select on reporting.v_automation_rule to authenticated, service_role;

create or replace view reporting.v_workflow_run
with (security_invoker = true) as
select id, workspace_id, event_type, automation_rule_id, action_type, outcome, created_at, updated_at
from public.workflow_run;
grant select on reporting.v_workflow_run to authenticated, service_role;
