-- generated by @movp/codegen - do not edit by hand

create table if not exists public.external_record (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspace(id) on delete cascade,
  source text not null,
  external_id text not null,
  payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.external_record enable row level security;
grant select, insert, update, delete on public.external_record to authenticated;
grant select, insert, update, delete on public.external_record to service_role;
create policy external_record_rw on public.external_record for all to authenticated
  using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));



create or replace function public.external_record_delete_chunks()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.search_chunk where source_table = 'external_record' and source_id = old.id;
  return old;
end;
$$;
revoke all on function public.external_record_delete_chunks() from public, anon, authenticated;

create trigger external_record_delete_chunks_tg
  after delete on public.external_record
  for each row execute function public.external_record_delete_chunks();

insert into public.movp_collections (name, label, label_plural, workspace_scoped)
values ('external_record', 'External Record', 'External Records', true)
on conflict (name) do update set label = excluded.label, label_plural = excluded.label_plural, workspace_scoped = excluded.workspace_scoped;

insert into public.movp_fields (collection_name, name, type, label, cardinality, reporting_role, searchable, embeddable)
values
  ('external_record', 'source', 'text', 'Source', null, null, false, false),
  ('external_record', 'external_id', 'text', 'External ID', null, null, false, false),
  ('external_record', 'payload', 'json', 'Payload', null, null, false, false)
on conflict (collection_name, name) do update set
  type = excluded.type,
  label = excluded.label,
  cardinality = excluded.cardinality,
  reporting_role = excluded.reporting_role,
  searchable = excluded.searchable,
  embeddable = excluded.embeddable;


create unique index if not exists event_type_key_unique on public.event_type (key);
insert into public.event_type (key, domain, label, payload_schema, schema_version, active, description)
values
  ('external.record.upserted', 'lifecycle', 'External Record Upserted', '{"type":"object"}', 1, true, null),
  ('ingest.idempotency_conflict', 'workflow', 'Ingest Idempotency Conflict', '{"type":"object"}', 1, true, null)
on conflict (key) do update set
  domain = excluded.domain,
  label = excluded.label,
  payload_schema = excluded.payload_schema,
  schema_version = excluded.schema_version,
  active = excluded.active,
  description = excluded.description;